// auto generated by dsg2.py, SRC002-103 commit hash 1548f0e7cf347616f872d835d6da2b5632115fc0
// Run with args: ['C:\\dev\\src002-103\\dsg2.py', '_main.dsg', '--gen_h', '--gen_c', '--gen_py']
#ifndef INC_GUARD__MAIN
#define INC_GUARD__MAIN

#include <stdint.h>

#if !__cplusplus
typedef int32_t fp1616_t;
typedef int32_t fp0824_t;
#else  // C++
    #error not supported
#endif

#ifndef PACKED
#define PACKED  __attribute__ ((__packed__))
#endif

// constants



// normal blocks
// Enum FATAL_ERROR_CODE(u32)
#define DSG_ENUM_FATAL_ERROR_CODE_NO_ERROR 0U
#define DSG_ENUM_FATAL_ERROR_CODE_WATCHDOG_RESET 1U

// Enum JABUS_CMD_HANDLER_RET(i32)
#define DSG_ENUM_JABUS_CMD_HANDLER_RET_OK 0
#define DSG_ENUM_JABUS_CMD_HANDLER_RET_NOK -1
#define DSG_ENUM_JABUS_CMD_HANDLER_RET_NOK_EXTDATA_BAD_FCS -2
#define DSG_ENUM_JABUS_CMD_HANDLER_RET_NOT_IMPLEMENTED -100

// Enum MAIN_STATE(u32)
#define DSG_ENUM_MAIN_STATE_NORMAL_MODE 0U
#define DSG_ENUM_MAIN_STATE_CONFIG_MODE 1U
#define DSG_ENUM_MAIN_STATE_FATAL_ERROR 2U
#define DSG_ENUM_MAIN_STATE_STARTUP    10U
#define DSG_ENUM_MAIN_STATE_HARDFAULT  11U

// Enum RESET_MODE(u32)
#define DSG_ENUM_RESET_MODE_NORMAL_OP_MODE 1303728842U
#define DSG_ENUM_RESET_MODE_BOOTLOADER_MODE 3186851212U

// Enum STARTUP_REASON(u16)
#define DSG_ENUM_STARTUP_REASON_COLD   0U
#define DSG_ENUM_STARTUP_REASON_WATCHDOG_RESET 1U
#define DSG_ENUM_STARTUP_REASON_SOFTWARE_RESET 2U
#define DSG_ENUM_STARTUP_REASON_PIN_RESET 3U

// bitdef PROBE_OP_FLAGS(u16)
#define DSG_PROBE_OP_FLAGS_IN_SMALL_BOOTLOADER_BIT         0
#define DSG_PROBE_OP_FLAGS_IN_SMALL_BOOTLOADER_MASK        0x00000001
#define DSG_PROBE_OP_FLAGS_IN_BIG_BOOTLOADER_BIT           1
#define DSG_PROBE_OP_FLAGS_IN_BIG_BOOTLOADER_MASK          0x00000002
#define DSG_PROBE_OP_FLAGS_SETTINGS_WRITE_OK_BIT           2
#define DSG_PROBE_OP_FLAGS_SETTINGS_WRITE_OK_MASK          0x00000004
#define DSG_PROBE_OP_FLAGS_ROUTING_OK_BIT                  3
#define DSG_PROBE_OP_FLAGS_ROUTING_OK_MASK                 0x00000008
#define DSG_PROBE_OP_FLAGS_NORMAL_OP_BIT                   4
#define DSG_PROBE_OP_FLAGS_NORMAL_OP_MASK                  0x00000010
#define DSG_PROBE_OP_FLAGS_FATAL_ERROR_BIT                 5
#define DSG_PROBE_OP_FLAGS_FATAL_ERROR_MASK                0x00000020
#define DSG_PROBE_OP_FLAGS_HALF_DUPLEX_BIT                 6
#define DSG_PROBE_OP_FLAGS_HALF_DUPLEX_MASK                0x00000040
#define DSG_PROBE_OP_FLAGS_RESTART_NEEDS_FF_BIT            7
#define DSG_PROBE_OP_FLAGS_RESTART_NEEDS_FF_MASK           0x00000080
#define DSG_PROBE_OP_FLAGS_FLOW_CTRL_BIT                   8
#define DSG_PROBE_OP_FLAGS_FLOW_CTRL_MASK                  0x00000100

// settings_block SerialNumbers
struct Setting_SerialNumbers
{
    uint32_t serialNumbers[16];    // 0
    uint32_t crc32;                // 64
}; // size=68, align=4
// settings_block SettingsBlock1
struct Setting_SettingsBlock1
{
    uint32_t setting1;             // 0
    uint32_t setting2;             // 4
    uint32_t setting3;             // 8
    uint32_t setting4;             // 12
    uint32_t crc32;                // 16
}; // size=20, align=4
// settings_block SettingsBlock2
struct Setting_SettingsBlock2
{
    uint32_t ching;                // 0
    uint16_t chong;                // 4
    uint8_t __pad01[2];            // 6
    uint32_t crc32;                // 8
}; // size=12, align=4
// struct JabusHeader
struct PACKED JabusHeader
{
    uint8_t dst;                   // 0
    uint8_t length;                // 1
    uint16_t cmd;                  // 2
}; // size=4, align=1
// struct JabusHeaderAnsExtended
struct PACKED JabusHeaderAnsExtended
{
    uint8_t dst;                   // 0
    uint8_t length;                // 1
    uint16_t cmd;                  // 2
    uint32_t ext_length;           // 4
}; // size=8, align=1
// struct JabusHeaderReqExtended
struct PACKED JabusHeaderReqExtended
{
    uint8_t dst;                   // 0
    uint8_t length;                // 1
    uint16_t cmd;                  // 2
    uint32_t ext_length;           // 4
    uint32_t ext_address;          // 8
}; // size=12, align=1
// struct LinkerSymbols
struct LinkerSymbols
{
    uint32_t *text_start;          // 0
    uint32_t *text_end;            // 4
    uint32_t *ram_data_start;      // 8
    uint32_t *ram_data_end;        // 12
    uint32_t *bss_start;           // 16
    uint32_t *bss_end;             // 20
    uint32_t *persistant_ram_start; // 24
    uint32_t *persistant_ram_end;  // 28
    uint32_t *extbuf_start;        // 32
    uint32_t *extbuf_end;          // 36
    uint32_t extbuf_size;          // 40
}; // size=44, align=4
// struct ProbeConstantData
struct PACKED ProbeConstantData
{
    uint8_t jabus_hw_type;         // 0
    uint32_t product_table_ptr;    // 1
    uint16_t product_table_size;   // 5
    uint16_t protocol_product_specific_type; // 7
}; // size=9, align=1
// settings_collection Main

#define SETTINGS_COLLECTION_MAIN_NUM_BLOCKS 3

#define SETTINGS_MAIN_BLOCK_IDX_SETTINGS1                      0
#define SETTINGS_MAIN_BLOCK_IDX_SETTINGS2                      1
#define SETTINGS_MAIN_BLOCK_IDX_SERIAL_NUMBERS                 2
struct SettingsMain
{
    struct Setting_SettingsBlock1 *settings1; // 0
    struct Setting_SettingsBlock2 *settings2; // 4
    struct Setting_SerialNumbers *serialNumbers; // 8
}; // size=4, align=1
// union MainUnion
union SettingsUnionMain
{
    struct Setting_SettingsBlock1 settings1; // 0
    struct Setting_SettingsBlock2 settings2; // 0
    struct Setting_SerialNumbers serialNumbers; // 0
}; // size=68, align=0
// Jabus Cmd Echo (0x0004)
// struct Echo
struct PACKED JabusRequestEcho
{
    struct JabusHeader header;     // 0
    uint8_t data[4];               // 4
}; // size=8, align=0
// struct Echo
struct PACKED JabusAnswerEcho
{
    struct JabusHeader header;     // 0
    uint8_t data[4];               // 4
}; // size=8, align=0
// Jabus Cmd EchoExt (0x0006)
// struct EchoExt
struct PACKED JabusRequestEchoExt
{
    struct JabusHeaderReqExtended header; // 0
}; // size=12, align=0
// struct EchoExt
struct PACKED JabusAnswerEchoExt
{
    struct JabusHeaderAnsExtended header; // 0
}; // size=8, align=0
// Jabus Cmd GetExtbufInfo (0x0018)
// struct GetExtbufInfo
struct PACKED JabusRequestGetExtbufInfo
{
    struct JabusHeader header;     // 0
}; // size=4, align=0
// struct GetExtbufInfo
struct PACKED JabusAnswerGetExtbufInfo
{
    struct JabusHeader header;     // 0
    uint32_t buf_ptr;              // 4
    uint32_t buf_len;              // 8
}; // size=12, align=0
// Jabus Cmd GetFuncPtr (0x001E)
// struct GetFuncPtr
struct PACKED JabusRequestGetFuncPtr
{
    struct JabusHeader header;     // 0
}; // size=4, align=0
// struct GetFuncPtr
struct PACKED JabusAnswerGetFuncPtr
{
    struct JabusHeader header;     // 0
    uint32_t func;                 // 4
}; // size=8, align=0
// Jabus Cmd GetSettingsInfo (0x0010)
// struct GetSettingsInfo
struct PACKED JabusRequestGetSettingsInfo
{
    struct JabusHeader header;     // 0
}; // size=4, align=0
// struct GetSettingsInfo
struct PACKED JabusAnswerGetSettingsInfo
{
    struct JabusHeader header;     // 0
    uint32_t num_settings;         // 4
}; // size=8, align=0
// Jabus Cmd JumpToMem (0x001C)
// struct JumpToMem
struct PACKED JabusRequestJumpToMem
{
    struct JabusHeader header;     // 0
    uint32_t addr;                 // 4
    int32_t arg0;                  // 8
    int32_t arg1;                  // 12
}; // size=16, align=0
// struct JumpToMem
struct PACKED JabusAnswerJumpToMem
{
    struct JabusHeader header;     // 0
    int32_t result;                // 4
}; // size=8, align=0
// Jabus Cmd NOK (0x0002)
// struct NOK
struct PACKED JabusRequestNOK
{
    struct JabusHeader header;     // 0
}; // size=4, align=0
// struct NOK
struct PACKED JabusAnswerNOK
{
    struct JabusHeader header;     // 0
    uint16_t the_bad_cmd;          // 4
    int32_t error_code;            // 6
    uint32_t info;                 // 10
}; // size=14, align=0
// Jabus Cmd ReadMem (0x000A)
// struct ReadMem
struct PACKED JabusRequestReadMem
{
    struct JabusHeader header;     // 0
    uint32_t addr;                 // 4
    uint16_t length;               // 8
}; // size=10, align=0
// struct ReadMem
struct PACKED JabusAnswerReadMem
{
    struct JabusHeaderAnsExtended header; // 0
}; // size=8, align=0
// Jabus Cmd ReadSettingsBlock (0x0012)
// struct ReadSettingsBlock
struct PACKED JabusRequestReadSettingsBlock
{
    struct JabusHeader header;     // 0
    uint32_t block_index;          // 4
}; // size=8, align=0
// struct ReadSettingsBlock
struct PACKED JabusAnswerReadSettingsBlock
{
    struct JabusHeaderAnsExtended header; // 0
    uint32_t block_index;          // 8
}; // size=12, align=0
// Jabus Cmd Reset (0x0008)
// struct Reset
struct PACKED JabusRequestReset
{
    struct JabusHeader header;     // 0
    uint32_t reset_mode_magic;     // 4
}; // size=8, align=0
// struct Reset
struct PACKED JabusAnswerReset
{
    struct JabusHeader header;     // 0
    uint32_t reset_mode_magic;     // 4
    uint32_t reset_counter;        // 8
}; // size=12, align=0
// Jabus Cmd WriteMem (0x000C)
// struct WriteMem
struct PACKED JabusRequestWriteMem
{
    struct JabusHeaderReqExtended header; // 0
}; // size=12, align=0
// struct WriteMem
struct PACKED JabusAnswerWriteMem
{
    struct JabusHeader header;     // 0
}; // size=4, align=0
// Jabus Cmd GetLinkerSymbols (0x001A)
// struct GetLinkerSymbols
struct PACKED JabusRequestGetLinkerSymbols
{
    struct JabusHeader header;     // 0
}; // size=4, align=0
// struct GetLinkerSymbols
struct PACKED JabusAnswerGetLinkerSymbols
{
    struct JabusHeader header;     // 0
    struct LinkerSymbols linker_symbols; // 4
}; // size=48, align=0
// Jabus Cmd Probe (0x0000)
// struct Probe
struct PACKED JabusRequestProbe
{
    struct JabusHeader header;     // 0
}; // size=4, align=0
// struct Probe
struct PACKED JabusAnswerProbe
{
    struct JabusHeader header;     // 0
    uint8_t main_cpu_nr;           // 4
    uint16_t op_flags;             // 5
    struct ProbeConstantData cdata; // 7
}; // size=16, align=0

// bitbanding
// enum enum FATAL_ERROR_CODE: no bitbanding for this type
// enum enum JABUS_CMD_HANDLER_RET: no bitbanding for this type
// enum enum MAIN_STATE: no bitbanding for this type
// enum enum RESET_MODE: no bitbanding for this type
// enum enum STARTUP_REASON: no bitbanding for this type
// bitdef bitdef PROBE_OP_FLAGS: no bitbanding for this type
// settings_block SerialNumbers_BB
struct Setting_SerialNumbers_BB
{
    uint32_t serialNumbers[16][32];
    uint32_t crc32[32];
}; // size=68, align=4
// settings_block SettingsBlock1_BB
struct Setting_SettingsBlock1_BB
{
    uint32_t setting1[32];
    uint32_t setting2[32];
    uint32_t setting3[32];
    uint32_t setting4[32];
    uint32_t crc32[32];
}; // size=20, align=4
// settings_block SettingsBlock2_BB
struct Setting_SettingsBlock2_BB
{
    uint32_t ching[32];
    uint32_t chong[16];
    uint32_t __pad01[2][8];
    uint32_t crc32[32];
}; // size=12, align=4
// struct JabusHeader_BB
struct JabusHeader_BB
{
    uint32_t dst[8];
    uint32_t length[8];
    uint32_t cmd[16];
}; // size=4, align=1
// struct JabusHeaderAnsExtended_BB
struct JabusHeaderAnsExtended_BB
{
    uint32_t dst[8];
    uint32_t length[8];
    uint32_t cmd[16];
    uint32_t ext_length[32];
}; // size=8, align=1
// struct JabusHeaderReqExtended_BB
struct JabusHeaderReqExtended_BB
{
    uint32_t dst[8];
    uint32_t length[8];
    uint32_t cmd[16];
    uint32_t ext_length[32];
    uint32_t ext_address[32];
}; // size=12, align=1
// struct LinkerSymbols_BB
struct LinkerSymbols_BB
{
    uint32_t text_start[32];
    uint32_t text_end[32];
    uint32_t ram_data_start[32];
    uint32_t ram_data_end[32];
    uint32_t bss_start[32];
    uint32_t bss_end[32];
    uint32_t persistant_ram_start[32];
    uint32_t persistant_ram_end[32];
    uint32_t extbuf_start[32];
    uint32_t extbuf_end[32];
    uint32_t extbuf_size[32];
}; // size=44, align=4
// struct ProbeConstantData_BB
struct ProbeConstantData_BB
{
    uint32_t jabus_hw_type[8];
    uint32_t product_table_ptr[32];
    uint32_t product_table_size[16];
    uint32_t protocol_product_specific_type[16];
}; // size=9, align=1
// settings_collection Main_BB
struct SettingsMain_BB
{
    uint32_t settings1[32];
    uint32_t settings2[32];
    uint32_t serialNumbers[32];
}; // size=4, align=1
// union MainUnion_BB
union SettingsUnionMain_BB
{
    struct Setting_SettingsBlock1_BB settings1;
    struct Setting_SettingsBlock2_BB settings2;
    struct Setting_SerialNumbers_BB serialNumbers;
}; // size=68, align=0
// jabus_cmd jabus_cmd Echo: no bitbanding for this type
// jabus_cmd jabus_cmd EchoExt: no bitbanding for this type
// jabus_cmd jabus_cmd GetExtbufInfo: no bitbanding for this type
// jabus_cmd jabus_cmd GetFuncPtr: no bitbanding for this type
// jabus_cmd jabus_cmd GetSettingsInfo: no bitbanding for this type
// jabus_cmd jabus_cmd JumpToMem: no bitbanding for this type
// jabus_cmd jabus_cmd NOK: no bitbanding for this type
// jabus_cmd jabus_cmd ReadMem: no bitbanding for this type
// jabus_cmd jabus_cmd ReadSettingsBlock: no bitbanding for this type
// jabus_cmd jabus_cmd Reset: no bitbanding for this type
// jabus_cmd jabus_cmd WriteMem: no bitbanding for this type
// jabus_cmd jabus_cmd GetLinkerSymbols: no bitbanding for this type
// jabus_cmd jabus_cmd Probe: no bitbanding for this type
union PACKED JabusCommands
{
  struct JabusRequestEcho reqEcho;
  struct JabusAnswerEcho ansEcho;
  struct JabusRequestEchoExt reqEchoExt;
  struct JabusAnswerEchoExt ansEchoExt;
  struct JabusRequestGetExtbufInfo reqGetExtbufInfo;
  struct JabusAnswerGetExtbufInfo ansGetExtbufInfo;
  struct JabusRequestGetFuncPtr reqGetFuncPtr;
  struct JabusAnswerGetFuncPtr ansGetFuncPtr;
  struct JabusRequestGetSettingsInfo reqGetSettingsInfo;
  struct JabusAnswerGetSettingsInfo ansGetSettingsInfo;
  struct JabusRequestJumpToMem reqJumpToMem;
  struct JabusAnswerJumpToMem ansJumpToMem;
  struct JabusRequestNOK reqNOK;
  struct JabusAnswerNOK ansNOK;
  struct JabusRequestReadMem reqReadMem;
  struct JabusAnswerReadMem ansReadMem;
  struct JabusRequestReadSettingsBlock reqReadSettingsBlock;
  struct JabusAnswerReadSettingsBlock ansReadSettingsBlock;
  struct JabusRequestReset reqReset;
  struct JabusAnswerReset ansReset;
  struct JabusRequestWriteMem reqWriteMem;
  struct JabusAnswerWriteMem ansWriteMem;
  struct JabusRequestGetLinkerSymbols reqGetLinkerSymbols;
  struct JabusAnswerGetLinkerSymbols ansGetLinkerSymbols;
  struct JabusRequestProbe reqProbe;
  struct JabusAnswerProbe ansProbe;
};
#define JABUS_CMD_ECHO                 0x0004
#define JABUS_CMD_ECHO_EXT             0x0006
#define JABUS_CMD_GET_EXTBUF_INFO      0x0018
#define JABUS_CMD_GET_FUNC_PTR         0x001e
#define JABUS_CMD_GET_SETTINGS_INFO    0x0010
#define JABUS_CMD_JUMP_TO_MEM          0x001c
#define JABUS_CMD_NOK                  0x0002
#define JABUS_CMD_READ_MEM             0x000a
#define JABUS_CMD_READ_SETTINGS_BLOCK  0x0012
#define JABUS_CMD_RESET                0x0008
#define JABUS_CMD_WRITE_MEM            0x000c
#define JABUS_CMD_GET_LINKER_SYMBOLS   0x001a
#define JABUS_CMD_PROBE                0x0000

// Settings global vars
extern const uint8_t settings_sizes[];
extern struct SettingsMain settings_new;
extern union SettingsUnionMain settings_union_data;

// Jabus buffer definitions
union PACKED JabusBufferUnion {
    struct PACKED JabusHeader header;
    struct PACKED JabusHeaderReqExtended header_req_ext;
    struct PACKED JabusHeaderAnsExtended header_ans_ext;
    union JabusCommands cmds;
    uint8_t data[sizeof(union JabusCommands) + 2]; // +2 for FCS
    uint16_t u16header[2];                         // for fletcher, we want to initialize c0/c1 with header data.
};

union u32_b {
    uint32_t u32;
    uint16_t u16[2];
    uint8_t u8[4];
};

struct JabusState {
    int state;
    int got_len;
    int got_pkt;
    union JabusBufferUnion *buf;
    uint32_t fcs0;
    uint32_t fcs1;
    int fletcher_count;
    uint8_t *ext_ptr; 
    uint32_t ext_down_count;
    union u32_b fcs32_tmp;
};
int jabus_pkt_handler_autogen(uint16_t cmd, struct JabusState *js);
int jabus_cmd_handler_echo(struct JabusState* state, struct JabusRequestEcho *req);
int jabus_cmd_handler_echo_ext(struct JabusState* state, struct JabusRequestEchoExt *req);
int jabus_cmd_handler_get_extbuf_info(struct JabusState* state, struct JabusRequestGetExtbufInfo *req);
int jabus_cmd_handler_get_func_ptr(struct JabusState* state, struct JabusRequestGetFuncPtr *req);
int jabus_cmd_handler_get_settings_info(struct JabusState* state, struct JabusRequestGetSettingsInfo *req);
int jabus_cmd_handler_jump_to_mem(struct JabusState* state, struct JabusRequestJumpToMem *req);
int jabus_cmd_handler_nok(struct JabusState* state, struct JabusRequestNOK *req);
int jabus_cmd_handler_read_mem(struct JabusState* state, struct JabusRequestReadMem *req);
int jabus_cmd_handler_read_settings_block(struct JabusState* state, struct JabusRequestReadSettingsBlock *req);
int jabus_cmd_handler_reset(struct JabusState* state, struct JabusRequestReset *req);
int jabus_cmd_handler_write_mem(struct JabusState* state, struct JabusRequestWriteMem *req);
int jabus_cmd_handler_get_linker_symbols(struct JabusState* state, struct JabusRequestGetLinkerSymbols *req);
int jabus_cmd_handler_probe(struct JabusState* state, struct JabusRequestProbe *req);

#endif // include guard
