// auto generated by dsg2.py, SRC002-103 commit hash d95471cc9565acca9d7227c8408fdc8b838e3d43
// Run with args: ['C:\\dev\\src002-103\\dsg2.py', '.\\_main.dsg', '--gen_h', '--gen_c']
#ifndef INC_GUARD__MAIN
#define INC_GUARD__MAIN

#include <stdint.h>

#if !__cplusplus
typedef int32_t fp1616_t;
typedef int32_t fp0824_t;
#else  // C++
    #error not supported
#endif

#ifndef PACKED
#define PACKED  __attribute__ ((__packed__))
#endif

// constants



// normal blocks
// settings_block SerialNumbers
struct Setting_SerialNumbers
{
    uint32_t serialNumbers[16];    // 0
    uint32_t crc32;                // 64
}; // size=68, align=4
// settings_block SettingsBlock1
struct Setting_SettingsBlock1
{
    uint32_t setting1;             // 0
    uint32_t setting2;             // 4
    uint32_t setting3;             // 8
    uint32_t setting4;             // 12
    uint32_t crc32;                // 16
}; // size=20, align=4
// settings_block SettingsBlock2
struct Setting_SettingsBlock2
{
    uint32_t ching;                // 0
    uint16_t chong;                // 4
    uint8_t __pad01[2];            // 6
    uint32_t crc32;                // 8
}; // size=12, align=4
// settings_collection Main

#define SETTINGS_COLLECTION_MAIN_NUM_BLOCKS 3

#define SETTINGS_MAIN_BLOCK_IDX_SETTINGS1                      0
#define SETTINGS_MAIN_BLOCK_IDX_SETTINGS2                      1
#define SETTINGS_MAIN_BLOCK_IDX_SERIAL_NUMBERS                 2
struct SettingsMain
{
    struct Setting_SettingsBlock1 *settings1; // 0
    struct Setting_SettingsBlock2 *settings2; // 4
    struct Setting_SerialNumbers *serialNumbers; // 8
}; // size=4, align=1
// union MainUnion
union SettingsUnionMain
{
    struct Setting_SettingsBlock1 settings1; // 0
    struct Setting_SettingsBlock2 settings2; // 0
    struct Setting_SerialNumbers serialNumbers; // 0
}; // size=68, align=0

// bitbanding
// settings_block SerialNumbers_BB
struct Setting_SerialNumbers_BB
{
    uint32_t serialNumbers[16][32];
    uint32_t crc32[32];
}; // size=68, align=4
// settings_block SettingsBlock1_BB
struct Setting_SettingsBlock1_BB
{
    uint32_t setting1[32];
    uint32_t setting2[32];
    uint32_t setting3[32];
    uint32_t setting4[32];
    uint32_t crc32[32];
}; // size=20, align=4
// settings_block SettingsBlock2_BB
struct Setting_SettingsBlock2_BB
{
    uint32_t ching[32];
    uint32_t chong[16];
    uint32_t __pad01[2][8];
    uint32_t crc32[32];
}; // size=12, align=4
// settings_collection Main_BB
struct SettingsMain_BB
{
    uint32_t settings1[32];
    uint32_t settings2[32];
    uint32_t serialNumbers[32];
}; // size=4, align=1
// union MainUnion_BB
union SettingsUnionMain_BB
{
    struct Setting_SettingsBlock1_BB settings1;
    struct Setting_SettingsBlock2_BB settings2;
    struct Setting_SerialNumbers_BB serialNumbers;
}; // size=68, align=0

#endif // include guard
