// auto generated by dsg2.py, SRC002-103 commit hash bd086af60b6e2154bc8d128df9fe78b59e6659d2
// Run with args: ['C:\\dev\\src002-103\\dsg2.py', '.\\_main.dsg', '--gen_c', '--gen_h']

#include "_main.h"

union SettingsUnionMain settings_union_data;

const struct Setting_SerialNumbers setting_default_SerialNumbers = { 
    .serialNumbers        = { 0 },       // 0
    .crc32                = 0,           // 64
 }; // size=68, align=4

const struct Setting_SettingsBlock1 setting_default_SettingsBlock1 = { 
    .setting1             = 0xDEADBEEF,  // 0, default=0xDEADBEEF
    .setting2             = 0,           // 4
    .setting3             = 0,           // 8
    .setting4             = 0,           // 12
    .crc32                = 0,           // 16
 }; // size=20, align=4

const void *settings_defaults[] = 
{
    &setting_default_SettingsBlock1,
    &setting_default_SerialNumbers,
};

const uint8_t settings_sizes[] = 
{
    sizeof(struct Setting_SettingsBlock1),
    sizeof(struct Setting_SerialNumbers),
};

// global
struct SettingsMain settings_new;

